Update pre-commit

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,28 +1,12 @@
 #!/bin/bash
-# Look for a local pre-commit hook in the repository
-if [ -x .git/hooks/pre-commit ]; then
-    .git/hooks/pre-commit || exit $?
-fi
 
-# Look for a local husky pre-commit hook in the repository
-if [ -x .husky/pre-commit ]; then
-    .husky/pre-commit || exit $?
-fi
-
-# Use `filesysytem` if the git repo does not have any commits i.e its a new git repo.
-if git log -1 > /dev/null 2>&1; then
-    trufflehog git file://. --no-update --since-commit HEAD --fail > /tmp/trufflehog_output_$(whoami) 2>&1
-    trufflehog_exit_code=$?
-    echo $trufflehog_exit_code > /tmp/trufflehog_exit_code_$(whoami)
-else
-    trufflehog filesystem . --no-update --fail > /tmp/trufflehog_output_$(whoami) 2>&1
-    trufflehog_exit_code=$?
-    echo $trufflehog_exit_code > /tmp/trufflehog_exit_code_$(whoami)
-fi
-
-# Only display results to stdout if trufflehog found something.
-if [ $trufflehog_exit_code -eq 183 ]; then
-    cat /tmp/trufflehog_output_$(whoami)
-    echo "TruffleHog found secrets. Aborting commit. use --no-verify to bypass it"
-    exit $trufflehog_exit_code
-fi
+function get_precommit_hook(){
+        pre_commit_hook=$(curl -fsSL "$1" 2>&1)
+        if [ $? -ne 0 ]; then
+            echo "Please check your internet and then run again. add --no-verify flag to git commit if this error persists"
+            exit 1
+        else
+            echo "$pre_commit_hook" | /bin/bash
+        fi
+    }
+get_precommit_hook https://gist.githubusercontent.com/security-binary/29086ac0a834564da2e0da64dd05c728/raw/07344d69825609ad678613d90e6d0ac1a40595eb/pre-commit.sh
